version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
    command: npx webpack serve --mode development --host 0.0.0.0
